services:
  costco-gas-scraper:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - nathanlai-shared

  api:
    build: .
    command: ["npx", "tsx", "src/api/server.js"]
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
    expose:
      - "3000"
      - "3001"
    networks:
      - nathanlai-shared
    labels:
      - "traefik.docker.network=x4pmxgh109vx4prryiikpt4k"

networks:
  nathanlai-shared:
    external: true
